on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_run:
    workflows:
      - Manual Release
    types:
      - completed

name: Create Release

jobs:

  build-project:
    name: Build Project
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install    
  
      - name: Generate build
        run: npm run build
        env:
          CI: false
      
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v4
        with:
          name: DiyHueUI
          path: |
            build
            dist

  release-project:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-project

    steps:
      - name: Determine tag name
        id: determine_tag
        run: |
          if [[ "${{ github.event_name }}" == "workflow_run" ]]; then
            echo "TAG_NAME=${{ github.event.workflow_run.outputs.next_tag }}" >> $GITHUB_ENV
          else
            echo "TAG_NAME=${{ github.ref_name }}" >> $GITHUB_ENV

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: DiyHueUI

      - name: Test artifact download
        run: ls -R

      - name: Archive artifact
        uses: thedoctor0/zip-release@main
        with:
          filename: DiyHueUI-release.zip

      - name: Create and Upload Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.TAG_NAME }}
          name: DiyHue UI release ${{ env.TAG_NAME }}
          files: DiyHueUI-release.zip
          make_latest: true
