on:
  workflow_dispatch: # Allow manual triggering of the workflow
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:

  determine-next-tag:
    name: Determine Next Tag
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest tag
        id: get_latest_tag
        run: |
          latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag: $latest_tag"
          echo "latest_tag=$latest_tag" >> $GITHUB_ENV

      - name: Calculate next tag
        id: calculate_next_tag
        run: |
          IFS='.' read -r major minor patch <<< "${latest_tag#v}"
          next_patch=$((patch + 1))
          next_tag="v${major}.${minor}.${next_patch}"
          echo "Next tag: $next_tag"
          echo "NEXT_TAG=$next_tag" >> $GITHUB_ENV
    outputs:
      next_tag: ${{ env.NEXT_TAG }}

  create-new-tag:
    name: Create New Tag
    runs-on: ubuntu-latest
    needs: determine-next-tag

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Create and push new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git tag ${{ env.NEXT_TAG }}
          git push origin ${{ env.NEXT_TAG }}

  build-project:
    name: Build Project
    runs-on: ubuntu-latest
    needs: create-new-tag

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install    
  
      - name: Generate build
        run: npm run build
        env:
          CI: false
      
      # Share artifact inside workflow
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v4
        with:
          name: DiyHueUI
          path: |
            build
            dist

  release-project:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build-project

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: DiyHueUI
      - name: Test artifact download
        run: ls -R

      - name: Archive artifact
        uses: thedoctor0/zip-release@main
        with:
          filename: DiyHueUI-release.zip

      - name: Create and Upload Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.NEXT_TAG }}
          name: DiyHue UI release ${{ env.NEXT_TAG }}
          files: DiyHueUI-release.zip
          make_latest: true
